import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1 className="text-4xl text-gray-800 font-serif">
          Heading from layout.jsx that always stays at top of every route
        </h1>
        {children}
      </body>
    </html>
  );
}
